package com.kmfex.webservice.client.hx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "hxbankinterfacePortType", targetNamespace = "http://webservice.kmfex.com")
public interface HxbankinterfacePortType {

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ032
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "tradingMarketBankBalance", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.TradingMarketBankBalance")
	@ResponseWrapper(localName = "tradingMarketBankBalanceResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.TradingMarketBankBalanceResponse")
	public ResponseDZ032 tradingMarketBankBalance(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ022
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "inGoldRegistrationRequest", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.InGoldRegistrationRequest")
	@ResponseWrapper(localName = "inGoldRegistrationRequestResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.InGoldRegistrationRequestResponse")
	public ResponseDZ022 inGoldRegistrationRequest(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ012
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "surrender", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.Surrender")
	@ResponseWrapper(localName = "surrenderResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SurrenderResponse")
	public ResponseDZ012 surrender(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ009
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "reconciliation", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.Reconciliation")
	@ResponseWrapper(localName = "reconciliationResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.ReconciliationResponse")
	public ResponseDZ009 reconciliation(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ008
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "liquidation", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.Liquidation")
	@ResponseWrapper(localName = "liquidationResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.LiquidationResponse")
	public ResponseDZ008 liquidation(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ016
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "signOff", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SignOff")
	@ResponseWrapper(localName = "signOffResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SignOffResponse")
	public ResponseDZ016 signOff(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ021
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "inGoldRequest", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.InGoldRequest")
	@ResponseWrapper(localName = "inGoldRequestResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.InGoldRequestResponse")
	public ResponseDZ021 inGoldRequest(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ017
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "outGold", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.OutGold")
	@ResponseWrapper(localName = "outGoldResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.OutGoldResponse")
	public ResponseDZ017 outGold(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ007
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "outGoldAuditResultSend", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.OutGoldAuditResultSend")
	@ResponseWrapper(localName = "outGoldAuditResultSendResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.OutGoldAuditResultSendResponse")
	public ResponseDZ007 outGoldAuditResultSend(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ018
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "inOutGoldDetailedCheck", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.InOutGoldDetailedCheck")
	@ResponseWrapper(localName = "inOutGoldDetailedCheckResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.InOutGoldDetailedCheckResponse")
	public ResponseDZ018 inOutGoldDetailedCheck(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ015
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "signIn", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SignIn")
	@ResponseWrapper(localName = "signInResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SignInResponse")
	public ResponseDZ015 signIn(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ020
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "subAccountSigned", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SubAccountSigned")
	@ResponseWrapper(localName = "subAccountSignedResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SubAccountSignedResponse")
	public ResponseDZ020 subAccountSigned(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

	/**
	 * 
	 * @param json
	 * @return returns com.kmfex.webservice.client.hx.ResponseDZ010
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.kmfex.com")
	@RequestWrapper(localName = "subAccountSync", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SubAccountSync")
	@ResponseWrapper(localName = "subAccountSyncResponse", targetNamespace = "http://webservice.kmfex.com", className = "com.kmfex.webservice.client.hx.SubAccountSyncResponse")
	public ResponseDZ010 subAccountSync(
			@WebParam(name = "json", targetNamespace = "http://webservice.kmfex.com") String json);

}
