package com.kmfex.webservice.client.sms;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>  
 * chargeinterface service = new chargeinterface();
 * ChargeinterfacePortType portType = service.getChargeinterfaceHttpPort();
 * portType.sendsms1(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "chargeinterface", targetNamespace = "http://webservice.kmfex.com", wsdlLocation = "http://"+Constant.WSDLURL+"/services/chargeinterface?wsdl")
public class Chargeinterface extends Service {

	private final static URL CHARGEINTERFACE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.kmfex.webservice.client.sms.Chargeinterface.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.kmfex.webservice.client.sms.Chargeinterface.class
					.getResource(".");
			System.out.println("-------=========="+Constant.WSDLURL);
			url = new URL(baseUrl, "http://"+Constant.WSDLURL+"/services/chargeinterface?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/C:/chargeinterface.xml', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CHARGEINTERFACE_WSDL_LOCATION = url;
	}

	public Chargeinterface(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Chargeinterface() {
		super(CHARGEINTERFACE_WSDL_LOCATION, new QName(
				"http://webservice.kmfex.com", "chargeinterface"));
	}

	/**
	 * 
	 * @return returns ChargeinterfacePortType
	 */
	@WebEndpoint(name = "chargeinterfaceHttpPort")
	public ChargeinterfacePortType getChargeinterfaceHttpPort() {
		return super.getPort(new QName("http://webservice.kmfex.com",
				"chargeinterfaceHttpPort"), ChargeinterfacePortType.class);
	}

}
