SET DEFINE OFF;
Insert into KT.T_MEMBER_TYPES
   (ID, CODE, CREATEDATE, NAME, UPDATEDATE)
 Values
   ('402881fb3652eee3013652eef6c10001', 'T', TO_DATE('03/27/2012 14:54:14', 'MM/DD/YYYY HH24:MI:SS'), '投资方', TO_DATE('04/02/2012 14:55:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into KT.T_MEMBER_TYPES
   (ID, CODE, CREATEDATE, NAME)
 Values
   ('402881fb3652eee3013652eef6ee0002', 'R', TO_DATE('03/27/2012 14:54:14', 'MM/DD/YYYY HH24:MI:SS'), '融资方');
   
Insert into KT.T_MEMBER_TYPES
   (ID, CODE, CREATEDATE, NAME)
 Values
   ('402881fb3652eee3013652eef6f70005', 'Q', TO_DATE('03/27/2012 14:54:14', 'MM/DD/YYYY HH24:MI:SS'), '其它');
COMMIT;

SET DEFINE OFF;
Insert into KT.T_MEMBER_LEVEL
   (ID, LEVELNAME, MEMBERTYPE_ID)
 Values
   ('402881fb365322350136534002990007', 'VIP', '402881fb3652eee3013652eef6c10001');
Insert into KT.T_MEMBER_LEVEL
   (ID, LEVELNAME, MEMBERTYPE_ID)
 Values
   ('402881fb365322350136534276670009', '高级', '402881fb3652eee3013652eef6c10001');
Insert into KT.T_MEMBER_LEVEL
   (ID, LEVELNAME, MEMBERTYPE_ID)
 Values
   ('402881fb36532235013653428d29000a', '普通', '402881fb3652eee3013652eef6c10001');
Insert into KT.T_MEMBER_LEVEL
   (ID, LEVELNAME, MEMBERTYPE_ID)
 Values
   ('ff8080813e3c77bb013e4953620e14ec', 'VIP特殊', '402881fb3652eee3013652eef6c10001');
Insert into KT.T_MEMBER_LEVEL
   (ID, LEVELNAME, MEMBERTYPE_ID)
 Values
   ('ff8080813fed4c0f013fefa08dbc0466', 'VIP-1', '402881fb3652eee3013652eef6c10001');
COMMIT;





////用户账户明细表

ALTER TABLE KT.T_ACCOUNTDEAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE KT.T_ACCOUNTDEAL CASCADE CONSTRAINTS;

CREATE TABLE KT.T_ACCOUNTDEAL
(
  ID                  VARCHAR2(255 BYTE)        NOT NULL,
  CREATEDATE          DATE,
  MONEY               FLOAT(126)                NOT NULL,
  NEXTMONEY           FLOAT(126)                NOT NULL,
  PREMONEY            FLOAT(126)                NOT NULL,
  TYPE                VARCHAR2(255 BYTE),
  ACCOUNT_ACCOUNTID_  NUMBER(19),
  FINANCING_ID        VARCHAR2(255 BYTE),
  USER_ID             NUMBER(19),
  CHECKFLAG           VARCHAR2(255 BYTE),
  BJ                  FLOAT(126),
  LX                  FLOAT(126),
  ACCOUNTDEAL_ID      VARCHAR2(255 BYTE),
  CHECKUSER_ID        NUMBER(19),
  FJ                  FLOAT(126),
  CHECKDATE           DATE,
  CHECKFLAG2          VARCHAR2(255 BYTE),
  HKDATE              DATE,
  MEMO                VARCHAR2(255 BYTE),
  HKUSER_ID           NUMBER(19),
  BATCHFLAG           VARCHAR2(255 BYTE),
  ZHAIQUANCODE        VARCHAR2(255 BYTE),
  BANKLIBRARY_ID      VARCHAR2(255 BYTE),
  BUSINESSFLAG        NUMBER(10)                DEFAULT 0,
  SUCCESSDATE         DATE,
  SUCCESSFLAG         NUMBER(1)                 DEFAULT 0,
  HUIDAN              VARCHAR2(255 BYTE),
  FKQRDATE            DATE,
  FKQRUSER_ID         NUMBER(19),
  BKSERIAL            VARCHAR2(255 BYTE),
  COSERIAL            VARCHAR2(255 BYTE),
  SIGNBANK            NUMBER(1)                 DEFAULT 0,
  SIGNTYPE            NUMBER(1)                 DEFAULT 0,
  TXDIR               NUMBER(1)                 DEFAULT 1,
  TXOPT               NUMBER(1)                 DEFAULT 0,
  TIME_               NUMBER(30)                DEFAULT 0,
  CHANNEL             NUMBER(1)                 DEFAULT 0,
  VERSION             NUMBER(10),
  BZJ                 FLOAT(126)                DEFAULT 0,
  CODES               VARCHAR2(255 BYTE)
)
TABLESPACE KMFEX
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          136M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX KT.IDX_ACCOUNTDEAL_ACCOUNTID ON KT.T_ACCOUNTDEAL
(ACCOUNT_ACCOUNTID_)
LOGGING
TABLESPACE KMFEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          17M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX KT.IDX_CHECKFLAG ON KT.T_ACCOUNTDEAL
(CHECKFLAG)
LOGGING
TABLESPACE KMFEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          15M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX KT.IDX_TYPE ON KT.T_ACCOUNTDEAL
(TYPE)
LOGGING
TABLESPACE KMFEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          25M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


--  There is no statement for index KT.SYS_C0030547.
--  The object is created when the parent object is created.

ALTER TABLE KT.T_ACCOUNTDEAL ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE KMFEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          88M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE KT.T_ACCOUNTDEAL ADD (
  CONSTRAINT FK854E14CE10A7F131 
  FOREIGN KEY (BANKLIBRARY_ID) 
  REFERENCES KT.T_BANKLIBRARY (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK854E14CE53BDD502 
  FOREIGN KEY (USER_ID) 
  REFERENCES KT.SYS_USER (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK854E14CE760A509C 
  FOREIGN KEY (FKQRUSER_ID) 
  REFERENCES KT.SYS_USER (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK854E14CE8A7CBCAE 
  FOREIGN KEY (ACCOUNT_ACCOUNTID_) 
  REFERENCES KT.SYS_ACCOUNT (ACCOUNTID_)
  ENABLE VALIDATE,
  CONSTRAINT FK854E14CEC5A7F31 
  FOREIGN KEY (ACCOUNTDEAL_ID) 
  REFERENCES KT.T_ACCOUNTDEAL (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK854E14CEECE7B6FA 
  FOREIGN KEY (CHECKUSER_ID) 
  REFERENCES KT.SYS_USER (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK854E14CEFAA8AE9F 
  FOREIGN KEY (HKUSER_ID) 
  REFERENCES KT.SYS_USER (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK854E14CEFBD9D802 
  FOREIGN KEY (FINANCING_ID) 
  REFERENCES KT.T_FINANCING_BASE (ID)
  ENABLE VALIDATE);

